// Random player name generator. Not from the workbook (it never named
// players) -- built to give every recruit/transfer a name for the roster
// and offseason-report tables. Two sizable pools combined give ~120x220
// distinct combinations, plenty for a 72-team league.

import type { Rand } from "./rng";

const FIRST_NAMES = [
  "Aiden", "Alex", "Amari", "Andre", "Anthony", "Antonio", "Ashton", "Austin",
  "Bennett", "Blake", "Brady", "Braxton", "Brayden", "Brody", "Bryce", "Caleb",
  "Cameron", "Carson", "Carter", "Chase", "Christian", "Cody", "Colby", "Colton",
  "Cooper", "Cole", "Corey", "Dallas", "Damian", "Daniel", "Dante", "Darius",
  "Davion", "Dawson", "Dax", "Deandre", "Declan", "Dejuan", "Derek", "Devin",
  "Diego", "Dominic", "Donovan", "Dorian", "Douglas", "Drake", "Dylan", "Eli",
  "Elijah", "Elliott", "Emmanuel", "Emmett", "Ethan", "Evan", "Ezekiel", "Fabian",
  "Felix", "Finn", "Gabriel", "Garrett", "Gavin", "Grant", "Grayson", "Greyson",
  "Hayden", "Henry", "Hunter", "Isaac", "Isaiah", "Ivan", "Jace", "Jack",
  "Jackson", "Jacob", "Jaden", "Jalen", "Jamal", "Jamar", "Jamari", "Jamison",
  "Jaxon", "Jaxson", "Jayden", "Jaylen", "Jeremiah", "Jesse", "Jett", "Joel",
  "Johnathan", "Jordan", "Jorge", "Josiah", "Julian", "Julius", "Justice", "Kaden",
  "Kai", "Kaleb", "Kamari", "Karsyn", "Kayden", "Keegan", "Kendrick", "Kevin",
  "Keyshawn", "Khalil", "Kingston", "Knox", "Kobe", "Kolton", "Kyler", "Lamar",
  "Landon", "Lane", "Lawrence", "Leo", "Leon", "Levi", "Lincoln", "Logan",
  "Lorenzo", "Lucas", "Luke", "Malachi", "Malik", "Marcus", "Mario", "Mason",
  "Mateo", "Mathias", "Maurice", "Maverick", "Maxwell", "Mekhi", "Micah", "Miles",
  "Nasir", "Nathaniel", "Nico", "Nolan", "Noel", "Omar", "Omari", "Orlando",
  "Otis", "Owen", "Parker", "Paxton", "Perry", "Peyton", "Preston", "Quincy",
  "Quinton", "Rafael", "Ramon", "Reece", "Reid", "Rhett", "Rico", "Roman",
  "Rory", "Ryder", "Rylan", "Santino", "Sawyer", "Sebastian", "Shane", "Silas",
  "Solomon", "Spencer", "Stetson", "Sterling", "Sylas", "Talon", "Tanner", "Tate",
  "Terrance", "Terrell", "Theo", "Thomas", "Titan", "Tobias", "Trace", "Trenton",
  "Trevon", "Tristan", "Tucker", "Tyree", "Tyshawn", "Uriah", "Vance", "Vaughn",
  "Victor", "Vincent", "Wade", "Walker", "Wesley", "Weston", "Wyatt", "Xavier",
  "Zach", "Zaire", "Zane", "Zavier",
];

const LAST_NAMES = [
  "Abbott", "Acosta", "Adams", "Alexander", "Allen", "Anderson", "Andrews", "Archer",
  "Armstrong", "Arnold", "Ashford", "Bailey", "Baker", "Baldwin", "Ballard", "Banks",
  "Barnes", "Barrett", "Bates", "Beasley", "Bell", "Bennett", "Bishop", "Blackwell",
  "Blair", "Boone", "Booth", "Bowen", "Bowman", "Boyd", "Bradley", "Brady",
  "Bragg", "Brewer", "Briggs", "Brooks", "Brown", "Bryant", "Buchanan", "Burke",
  "Burnett", "Burns", "Butler", "Byrd", "Cain", "Calhoun", "Callahan", "Cameron",
  "Campbell", "Cannon", "Carey", "Carlisle", "Carpenter", "Carroll", "Carson", "Carter",
  "Case", "Casey", "Chambers", "Chandler", "Chapman", "Charles", "Chavez", "Christensen",
  "Clark", "Clarke", "Clayton", "Cobb", "Cole", "Coleman", "Collins", "Colon",
  "Combs", "Conley", "Conway", "Cook", "Cooper", "Cordova", "Cortez", "Cox",
  "Craig", "Crawford", "Crosby", "Cross", "Cruz", "Cunningham", "Curry", "Dale",
  "Daniels", "Davenport", "Davidson", "Davis", "Dawson", "Day", "Delgado", "Diaz",
  "Dixon", "Dominguez", "Donovan", "Dorsey", "Douglas", "Doyle", "Duffy", "Duncan",
  "Dunn", "Durham", "Eaton", "Edwards", "Ellis", "Elmore", "Emerson", "Erickson",
  "Espinoza", "Estrada", "Evans", "Ferguson", "Fields", "Fischer", "Fisher", "Fitzgerald",
  "Fletcher", "Flores", "Flynn", "Foster", "Fox", "Francis", "Franklin", "Frazier",
  "Freeman", "Fuller", "Gaines", "Gallagher", "Gallegos", "Gamble", "Garcia", "Gardner",
  "Garrett", "Garrison", "Gibson", "Gilbert", "Gill", "Glover", "Gomez", "Gonzalez",
  "Goodman", "Gordon", "Graham", "Grant", "Graves", "Gray", "Green", "Greer",
  "Gregory", "Griffin", "Guerrero", "Guthrie", "Hale", "Hall", "Hamilton", "Hammond",
  "Hansen", "Hardin", "Harmon", "Harper", "Harris", "Harrison", "Hart", "Harvey",
  "Hawkins", "Hayes", "Haynes", "Henderson", "Hendricks", "Henry", "Hernandez", "Herrera",
  "Hicks", "Higgins", "Hill", "Hobbs", "Hodge", "Hoffman", "Hogan", "Holland",
  "Holloway", "Holmes", "Holt", "Hooper", "Horton", "House", "Houston", "Howard",
  "Howell", "Hubbard", "Hudson", "Huff", "Hughes", "Hunt", "Hunter", "Ingram",
  "Irwin", "Jacobs", "James", "Jefferson", "Jennings", "Jimenez", "Johnson", "Johnston",
  "Jones", "Jordan", "Joseph", "Kane", "Keller", "Kelley", "Kelly", "Kennedy",
  "Kerr", "Kim", "King", "Kirby", "Knight", "Knox", "Lambert", "Landry",
  "Lane", "Lang", "Larson", "Lawrence", "Lawson", "Leach", "Lee", "Leon",
  "Leonard", "Lewis", "Lindsey", "Little", "Logan", "Long", "Lopez", "Love",
  "Lowe", "Lowery", "Lucas", "Lynch", "Lyons", "Macias", "Mack", "Maldonado",
  "Malone", "Mann", "Manning", "Marsh", "Marshall", "Martin", "Martinez", "Mason",
  "Massey", "Mathis", "Matthews", "Maxwell", "May", "Mccarthy", "Mcdaniel", "Mcdonald",
  "Mcguire", "Mckenzie", "Mclean", "Mcpherson", "Meadows", "Medina", "Mejia", "Mendez",
  "Mercer", "Merritt", "Meyer", "Miles", "Miller", "Mills", "Mitchell", "Molina",
  "Montgomery", "Moody", "Moore", "Morales", "Moran", "Moreno", "Morgan", "Morris",
  "Morrison", "Morton", "Moss", "Mueller", "Munoz", "Murphy", "Murray", "Myers",
  "Nash", "Navarro", "Nelson", "Newman", "Newton", "Nguyen", "Nichols", "Nolan",
  "Norman", "Norris", "Nunez", "Ochoa", "Oliver", "Olsen", "Orozco", "Ortiz",
  "Osborne", "Owen", "Owens", "Pace", "Padilla", "Palmer", "Park", "Parker",
  "Parks", "Parrish", "Patterson", "Patton", "Payne", "Pearson", "Peck", "Pena",
  "Perez", "Perkins", "Perry", "Peters", "Peterson", "Phelps", "Phillips", "Pierce",
  "Pittman", "Pope", "Porter", "Potter", "Powell", "Powers", "Pratt", "Preston",
  "Price", "Prince", "Pruitt", "Quinn", "Ramirez", "Ramos", "Randall", "Ray",
  "Reed", "Reese", "Reeves", "Reid", "Reilly", "Reyes", "Reynolds", "Rice",
  "Richards", "Richardson", "Riggs", "Riley", "Rios", "Rivas", "Rivera", "Roach",
  "Robbins", "Roberson", "Roberts", "Robertson", "Robinson", "Rodgers", "Rodriguez", "Rogers",
  "Rojas", "Rollins", "Roman", "Romero", "Rosales", "Ross", "Roy", "Rush",
  "Russell", "Ryan", "Salazar", "Sanchez", "Sanders", "Santiago", "Santos", "Sawyer",
  "Schmidt", "Schneider", "Schroeder", "Schultz", "Scott", "Sellers", "Serrano", "Sexton",
  "Shaffer", "Shannon", "Sharp", "Shaw", "Shelton", "Sherman", "Silva", "Simmons",
  "Simon", "Simpson", "Sims", "Singleton", "Skinner", "Sloan", "Small", "Smith",
  "Snow", "Snyder", "Solomon", "Solis", "Soto", "Sparks", "Spears", "Spencer",
  "Stafford", "Stanley", "Stark", "Steele", "Stephens", "Stevens", "Stewart", "Stokes",
  "Stone", "Strickland", "Strong", "Suarez", "Sullivan", "Summers", "Sutton", "Swanson",
  "Sweeney", "Talley", "Tapia", "Tate", "Taylor", "Terry", "Thomas", "Thompson",
  "Thornton", "Todd", "Torres", "Townsend", "Tran", "Travis", "Trujillo", "Tucker",
  "Turner", "Underwood", "Valdez", "Valencia", "Valentine", "Valenzuela", "Vance", "Vargas",
  "Vasquez", "Vaughn", "Vega", "Velasquez", "Villarreal", "Vincent", "Wade", "Wagner",
  "Walker", "Wallace", "Waller", "Walsh", "Walters", "Walton", "Ward", "Warner",
  "Warren", "Washington", "Waters", "Watkins", "Watson", "Weaver", "Webb", "Webster",
  "Weeks", "Weiss", "Wells", "West", "Wheeler", "White", "Whitfield", "Whitney",
  "Wilcox", "Wiley", "Wilkerson", "Wilkins", "Williams", "Williamson", "Willis", "Wilson",
  "Winters", "Wise", "Wolf", "Wolfe", "Wong", "Wood", "Woodard", "Woods",
  "Wooten", "Wright", "Wyatt", "Yates", "York", "Young", "Zamora", "Zimmerman",
];

export function generatePlayerName(rand: Rand = Math.random): string {
  const first = FIRST_NAMES[Math.floor(rand() * FIRST_NAMES.length)];
  const last = LAST_NAMES[Math.floor(rand() * LAST_NAMES.length)];
  return `${first} ${last}`;
}
